BOOTMAGIC_ENABLE = yes
EXTRAKEY_ENABLE  = yes
ENCODER_ENABLE   = yes
OLED_ENABLE      = yes
OLED_DRIVER      = ssd1306

MOUSEKEY_ENABLE  = no
COMMAND_ENABLE   = no
CONSOLE_ENABLE   = no
AUDIO_ENABLE     = no
RGBLIGHT_ENABLE  = no
